In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
engine = create_engine(
    "mysql+pymysql://root:soumo444@localhost:3306/customer_churn_retention"
)

In [4]:
test = pd.read_sql("SELECT 1", engine)

test

   1
0  1

In [5]:
query = """
SELECT *
FROM customers;
"""

df = pd.read_sql(query, engine)

In [7]:
pd.read_sql("SELECT * FROM customers", engine)

,customer_id,gender,age,country,city,customer_segment,tenure_months,signup_channel,contract_type,monthly_logins,...,avg_resolution_time,complaint_type,csat_score,escalations,email_open_rate,marketing_click_rate,nps_score,survey_response,referral_count,churn
0,CUST_00001,Male,68,Bangladesh,London,SME,22,Web,Monthly,26,...,13.35,Service,4,0,0.71,0.40,27,Satisfied,1,0
1,CUST_00002,Female,57,Canada,Sydney,Individual,9,Mobile,Monthly,7,...,25.14,Billing,2,0,0.78,0.33,-19,Neutral,2,1
2,CUST_00003,Male,24,Germany,New York,SME,58,Web,Yearly,19,...,27.57,Service,3,0,0.35,0.49,80,Neutral,1,0
3,CUST_00004,Male,49,Australia,Dhaka,Individual,19,Mobile,Yearly,34,...,26.42,Technical,5,1,0.83,0.15,100,Neutral,0,0
4,CUST_00005,Male,65,Bangladesh,Delhi,Individual,52,Web,Monthly,20,...,26.67,Technical,4,0,0.65,0.44,21,Unsatisfied,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,CUST_09996,Female,67,Germany,Sydney,SME,37,Web,Yearly,15,...,34.24,Service,4,1,0.36,0.28,20,Satisfied,2,0
9996,CUST_09997,Male,26,USA,Toronto,Individual,42,Mobile,Yearly,13,...,40.09,None,4,0,0.48,0.06,28,Unsatisfied,2,0
9997,CUST_09998,Female,18,Canada,Sydney,Individual,39,Mobile,Yearly,15,...,25.22,Technical,1,0,0.11,0.07,-30,Satisfied,1,0
9998,CUST_09999,Female,30,USA,Delhi,Individual,52,Web,Monthly,14,...,20.54,None,2,0,0.25,0.31,58,Neutral,1,1
9999,CUST_10000,Male,67,UK,Berlin,SME,7,Mobile,Monthly,15,...,23.54,Technical,4,1,0.40,0.30,1,Satisfied,1,0